name: sinbool
description: "Islamic stories app for children - Learn Quran stories, prophets, and values"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  audio_service: ^0.18.17
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  drift: ^2.22.1
  equatable: ^2.0.7
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.3
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.2
  injectable: ^2.5.0
  intl: ^0.20.1
  just_audio: ^0.9.42
  logger: ^2.5.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.28
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.3
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
